CREATE TABLE IF NOT EXISTS genres (
	id SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL);

CREATE TABLE IF NOT EXISTS singers (
	id SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL);

CREATE TABLE IF NOT EXISTS mixgengers (
	id SERIAL PRIMARY KEY,
	nameID INTEGER NOT NULL REFERENCES singers(id),
	genreID INTEGER NOT NULL REFERENCES genres(id));

CREATE TABLE IF NOT EXISTS alboms (
	id SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL,
	year_of_create DATE NOT NULL);

CREATE TABLE IF NOT EXISTS mixalboms (
	id SERIAL PRIMARY KEY,
	nameID INTEGER NOT NULL REFERENCES singers(id),
	albomID INTEGER NOT NULL REFERENCES alboms(id));

CREATE TABLE IF NOT EXISTS Treks(
	id SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL,
	duration INTEGER NOT null,
	albom INTEGER NOT NULL REFERENCES alboms(id));

CREATE TABLE IF NOT EXISTS compilations(
	id SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL,
	year_of_create DATE NOT NULL);
 
CREATE TABLE IF NOT EXISTS mixcompilations(
	id SERIAL PRIMARY KEY,
	compilationID INTEGER NOT NULL REFERENCES compilations(id),
	trekID INTEGER NOT NULL REFERENCES treks(id));